# This Pipeline will manage CloudRun deployment via Terraform

name: 'CICD EP1'

on:
  push:
    branches:
      - 'main'
      - 'sm'
    paths:
      - 'sm/**'

concurrency: ${{ github.repository }}

jobs:
  ep1_cicd:
    name: 'CICD Job EP1'
    runs-on: 'ubuntu-latest'

    steps:

      - name: GIT Checkout
        id: 'git-checkout'
        uses: "actions/checkout@v4"

      - name: Terraform Init
        id: 'tf-init'
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.EP_KEY1 }}
        run: |
          cd ./sm
          terraform init
          pwd

      - name: Terraform Plan
        id: 'tf-plan'
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.EP_KEY1 }}
        run: |
          cd ./sm
          terraform plan

      - name: Terraform Apply
        id: 'tf-apply'
        if: |
          github.ref == 'refs/heads/main'
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.EP_KEY1 }}
        run: |
          cd ./sm
          terraform apply --auto-approve

      - name: Upload File
        id: 'python-upload'
        if: |
          github.ref == 'refs/heads/main'
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.EP_KEY1 }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/cred.json
        run: |
          cd ./sm
          echo -n "$GOOGLE_CREDENTIALS" > $GOOGLE_APPLICATION_CREDENTIALS
          pip install gcloud
          python gcsUpoad.py
          rm $GOOGLE_APPLICATION_CREDENTIALS
